ci(aws): 💚 improved deploy script

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,25 +23,35 @@ jobs:
         env:
           EC2_HOST: ${{ secrets.EC2_HOST }}
           EC2_USER: ${{ secrets.EC2_USER }}
+          
         run: |
           ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
-            cd 2024-1B-T02-EC10-G05/src
+            cd ~/2024-1B-T02-EC10-G05/src
             git checkout dev
             git pull
+            echo "Stopping and removing old containers"
             docker compose down
-            docker compose up -d --build
+            echo "Building and starting containers"
+            docker compose -f docker-compose.prod.yaml up -d --build
+
+            COMPOSE_UP_EXIT_CODE=$?
+            if [ $COMPOSE_UP_EXIT_CODE -ne 0 ]; then
+                echo "docker-compose up failed"
+                exit 1
+            fi
+
             sleep 10  # Aguardar alguns segundos para garantir que os serviços estejam iniciados
             # Verificar o status dos containers
             STATUS=$(docker compose ps | grep -E "Exit|Restarting" || true)
             if [ -n "$STATUS" ]; then
-              echo "One or more services are not running correctly"
-              exit 1
+                echo "One or more services are not running correctly"
+                exit 1
             fi
             # Verificar logs dos containers para mensagens de erro (opcional)
             LOGS=$(docker compose logs 2>&1 | grep -i "error" || true)
             if [ -n "$LOGS" ]; then
-              echo "Error found in container logs"
-              echo "$LOGS"
-              exit 1
+                echo "Error found in container logs"
+                echo "$LOGS"
+                exit 1
             fi
           EOF
